name: RREC
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - pip:
    - accelerate==1.6.0
    - bitsandbytes==0.49.1
    - datasets==3.4.1
    - einops==0.8.1
    - fire==0.7.0
    - huggingface-hub==0.36.0
    - numpy==1.26.4
    - pandas==2.2.3
    - peft==0.15.0
    - pyarrow==22.0.0
    - rich==13.9.4
    - safetensors==0.7.0
    - scipy==1.17.0
    - sentencepiece==0.2.1
    - tokenizers==0.22.2
    - tqdm==4.67.1
    - transformers==4.57.6
    - trl==0.16.1
    - vllm==0.7.3
    - xformers==0.0.28.post3
